version: 2
builds:
  - id: kubectl-mounts
    main: .
    binary: kubectl-mounts
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w -X 'github.com/yeqianmen/kubectl-mounts/cmd.version={{ .Version }}'
        


archives:
  - id: kubectl-mounts
    builds:
      - kubectl-mounts
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE
snapshot:
    version_template: "{{ .Version }}"
krews:
  - name: mounts
    ids:
      - kubectl-mounts
    homepage: "https://github.com/yeqianmen/kubectl-mounts/"
    description: | 
      A kubectl plugin that displays detailed information about pod volumes
      and volumeMounts, helping developers inspect Kubernetes storage usage.
    short_description: "Show volumes and volumeMounts for pods in the current namespace"
    url_template: "https://github.com/MartinSimango/kubectl-plugin_completion/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: true

release:
  extra_files:
    - glob: ./dist/krew/mounts.yaml

