version: 2
builds:
  - id: kubectl-mounts
    main: .
    binary: kubectl-mounts
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
    ldflags:
      - -s -w -X 'github.com/yeqianmen/kubectl-mounts/cmd.version={{ .Version }}'
        


archives:
  - id: kubectl-mounts
    builds:
      - kubectl-mounts
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    format: tar.gz
    files:
      - LICENSE
release:
  extra_files:
    - glob: kubectl-mounts.yaml
  draft: true
