apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: images
spec:
  version: {{ .TagName }}
  homepage: https://github.com/yeqianmen/kubectl-mounts/
  shortDescription: Show volumes and volumeMounts for pods in the current namespace.
  description: |
    A kubectl plugin that displays detailed information about pod volumes
    and volumeMounts, helping developers inspect Kubernetes storage usage.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      files:
        - from: kubectl-mounts
          to: .
        - from: LICENSE
          to: .
      {{ addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-images_darwin_amd64.tar.gz" .TagName }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      files:
        - from: kubectl-mounts
          to: .
        - from: LICENSE
          to: .
      {{ addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-images_darwin_arm64.tar.gz" .TagName }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      files:
        - from: kubectl-mounts
          to: .
        - from: LICENSE
          to: .
      {{ addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-images_linux_amd64.tar.gz" .TagName }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      files:
        - from: kubectl-mounts
          to: .
        - from: LICENSE
          to: .
      {{ addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-images_linux_arm64.tar.gz" .TagName }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: linux
          arch: arm
      files:
        - from: kubectl-mounts
          to: .
        - from: LICENSE
          to: .
      {{ addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-images_linux_arm.tar.gz" .TagName }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      files:
        - from: kubectl-mounts.exe
          to: .
        - from: LICENSE
          to: .
      {{ addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-images_windows_amd64.tar.gz" .TagName }}
      bin: kubectl-mounts.exe
