apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: mounts
spec:
  version: {{ .TagName }}
  homepage: https://github.com/your-org/kubectl-mounts
  shortDescription: Show Pods' Volumes and VolumeMounts in the current namespace
  description: |
    kubectl-mounts is a kubectl plugin that lists all Pods in the
    current namespace along with their Volumes and VolumeMounts.
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/your-org/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_{{ .TagName }}_linux_amd64.tar.gz
      sha256: {{ .AssetSha256 "kubectl-mounts_{{ .TagName }}_linux_amd64.tar.gz" }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/your-org/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_{{ .TagName }}_linux_arm64.tar.gz
      sha256: {{ .AssetSha256 "kubectl-mounts_{{ .TagName }}_linux_arm64.tar.gz" }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/your-org/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_{{ .TagName }}_darwin_amd64.tar.gz
      sha256: {{ .AssetSha256 "kubectl-mounts_{{ .TagName }}_darwin_amd64.tar.gz" }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/your-org/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_{{ .TagName }}_darwin_arm64.tar.gz
      sha256: {{ .AssetSha256 "kubectl-mounts_{{ .TagName }}_darwin_arm64.tar.gz" }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/your-org/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_{{ .TagName }}_windows_amd64.zip
      sha256: {{ .AssetSha256 "kubectl-mounts_{{ .TagName }}_windows_amd64.zip" }}
      bin: kubectl-mounts.exe
