apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: mounts
spec:
  version: {{ .TagName }}
  homepage: https://github.com/yeqianmen/kubectl-mounts
  shortDescription: Show Pods' Volumes and VolumeMounts in the current namespace
  description: |
    kubectl-mounts is a kubectl plugin that lists all Pods in the
    current namespace along with their Volumes and VolumeMounts.
  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_linux_amd64.tar.gz" .TagName | indent 6}}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_linux_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_darwin_amd64.tar.gz" .TagName | indent 6}}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_darwin_arm64.tar.gz" .TagName | indent 6}}
      bin: kubectl-mounts
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/yeqianmen/kubectl-mounts/releases/download/{{ .TagName }}/kubectl-mounts_windows_amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-mounts.exe
